import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import ReportEvidencePreview from '@/components/reports/ReportEvidencePreview';
import { COLORS, RADIUS, SPACING, TYPOGRAPHY } from '@/constants/theme';
import type { ReportLink, ReportSection, ReportViewModel } from '@/types/report';
import { formatLocalDateTime } from '@/utils/dateTime';
import { buildConsolidatedParts, buildFindingsRows, buildRemarksRows, FINDINGS_COLUMNS, MATRIX_LEGEND, REMARKS_COLUMNS, type MatrixTable } from '@/utils/reportMatrix';

function PartTitle({ number, title }: { number: number; title: string }) { return <Text style={styles.part}>Part {number} — {title}</Text>; }

function HorizontalTable({ columns, rows, links, onOpen }: { columns: string[]; rows: string[][]; links?: (ReportLink | null)[]; onOpen?: (link: ReportLink) => void }) {
  return <ScrollView horizontal showsHorizontalScrollIndicator><View><View style={styles.tableHeader}>{columns.map((column) => <Text key={column} style={[styles.cell, styles.headerCell]}>{column}</Text>)}</View>{rows.length ? rows.map((row, rowIndex) => { const link = links?.[rowIndex] ?? null; return <Pressable key={rowIndex} disabled={!link || !onOpen} onPress={() => link && onOpen?.(link)} style={[styles.tableRow, rowIndex % 2 === 1 && styles.altRow, link && onOpen && styles.linkedRow]}>{row.map((cell, index) => <Text key={`${index}-${cell}`} style={styles.cell}>{cell || '—'}</Text>)}</Pressable>; }) : <Text style={styles.empty}>No records matched the selected filters.</Text>}</View></ScrollView>;
}

function SummarySection({ section, onOpen }: { section: ReportSection; onOpen?: (link: ReportLink) => void }) { return <View style={styles.section}><Text style={styles.heading}>{section.title}</Text><HorizontalTable columns={section.columns} rows={section.rows} links={section.rowLinks} onOpen={onOpen} /></View>; }

function Matrix({ table, onOpen }: { table: MatrixTable; onOpen?: (link: ReportLink) => void }) {
  const groups: { label: string; count: number }[] = [];
  for (const column of table.columns) { const last = groups.at(-1); if (last?.label === column.group) last.count += 1; else groups.push({ label: column.group, count: 1 }); }
  return <View style={styles.section}><Text style={styles.heading}>{table.title}</Text><ScrollView horizontal showsHorizontalScrollIndicator><View><View style={styles.groupRow}>{groups.map((group) => <Text key={group.label} style={[styles.groupCell, { width: group.count * 116 }]}>{group.label}</Text>)}</View><View style={styles.tableHeader}>{table.columns.map((column) => <Text key={`${column.group}-${column.label}`} style={[styles.cell, styles.headerCell]}>{column.label}</Text>)}</View>{table.rows.length ? table.rows.map((row, index) => <Pressable key={row.inspectionId} onPress={() => onOpen?.({ kind: 'inspection', id: row.inspectionId })} disabled={!onOpen} style={[styles.tableRow, index % 2 === 1 && styles.altRow, onOpen && styles.linkedRow]}>{row.values.map((cell, cellIndex) => <Text key={`${cellIndex}-${cell}`} style={styles.cell}>{cell || '—'}</Text>)}</Pressable>) : <Text style={styles.empty}>No inspection records matched this report scope.</Text>}</View></ScrollView></View>;
}

export default function ReportPreview({ report, onOpen }: { report: ReportViewModel; onOpen?: (link: ReportLink) => void }) {
  const records = report.inspectionRecords ?? []; const layout = buildConsolidatedParts(report); const findings = buildFindingsRows(records); const remarks = buildRemarksRows(records);
  return <View style={styles.paper}>
    <View style={styles.header}><Text style={styles.brand}>SUTA</Text><Text style={styles.jurisdiction}>{report.jurisdiction}</Text><Text style={styles.office}>{report.officeLabel}</Text><Text style={styles.title}>{report.title}</Text></View>
    <View style={styles.meta}><Text style={styles.metaText}><Text style={styles.bold}>Reporting Period: </Text>{report.reportingPeriod}</Text><Text style={styles.metaText}><Text style={styles.bold}>Generated: </Text>{formatLocalDateTime(report.generatedAt)}</Text>{report.scope.map((item) => <Text key={item} style={styles.metaText}>{item}</Text>)}</View>
    {layout.parts.map((part) => <View key={`${part.number}-${part.title}`} style={styles.partSection}><PartTitle number={part.number} title={part.title} />{part.number === 1 ? <><View style={styles.metrics}>{report.metrics.map((item) => <View key={item.label} style={styles.metric}><Text style={styles.metricValue}>{item.value}</Text><Text style={styles.metricLabel}>{item.label}</Text></View>)}</View>{report.highlights.length ? <View style={styles.highlights}>{report.highlights.map((item) => <Text key={item} style={styles.highlight}>• {item}</Text>)}</View> : null}</> : null}{part.sections?.map((section) => <SummarySection key={section.title} section={section} onOpen={onOpen} />)}{part.tables?.map((table) => <Matrix key={table.title} table={table} onOpen={onOpen} />)}{part.tables?.length ? <View style={styles.legend}>{MATRIX_LEGEND.map((item) => <Text key={item} style={styles.legendText}>{item}</Text>)}</View> : null}</View>)}
    <View style={styles.partSection}><PartTitle number={layout.findingsPart} title="Findings / Observations" /><HorizontalTable columns={FINDINGS_COLUMNS} rows={findings.map((row) => row.values)} links={findings.map((row) => ({ kind: 'inspection', id: row.inspectionId }))} onOpen={onOpen} /></View>
    <View style={styles.partSection}><PartTitle number={layout.remarksPart} title="Remarks" /><HorizontalTable columns={REMARKS_COLUMNS} rows={remarks.map((row) => row.values)} links={remarks.map((row) => ({ kind: 'inspection', id: row.inspectionId }))} onOpen={onOpen} /></View>
    {report.includePhotoEvidence ? <View style={styles.partSection}><PartTitle number={layout.evidencePart} title="Photo Evidence" />{records.some((record) => record.findings.some((finding) => finding.evidence.length)) ? records.map((record) => <ReportEvidencePreview key={record.id} record={record} />) : <Text style={styles.empty}>No photo evidence is attached to the exported inspection set.</Text>}</View> : null}
    {report.generatedBy === 'bsi' ? <View style={styles.signature}><Text style={styles.heading}>Prepared by</Text><Text style={styles.signatureLine}>{report.preparedBy ?? 'Barangay Sanitary Inspector'}</Text><Text style={styles.signatureCaption}>Barangay Sanitary Inspector · Date: ____________________</Text><Text style={[styles.heading, styles.reviewed]}>Received / Reviewed by</Text><Text style={styles.signatureLine}>Municipal/City Sanitation Administrator</Text><Text style={styles.signatureCaption}>Date: ____________________</Text></View> : null}
    <View style={styles.footer}><Text style={styles.footerText}>Generated by SUTA · Internal sanitation operations report</Text>{report.totalCount !== undefined ? <Text style={styles.footerText}>Included {report.exportedCount ?? 0} of {report.totalCount} matching records</Text> : null}</View>
  </View>;
}

const styles = StyleSheet.create({
  paper: { backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.md, padding: SPACING.lg, gap: SPACING.xl }, header: { alignItems: 'center', borderBottomWidth: 2, borderBottomColor: COLORS.primary, paddingBottom: SPACING.md }, brand: { ...TYPOGRAPHY.display, color: COLORS.primary }, jurisdiction: { ...TYPOGRAPHY.subheading, color: COLORS.text, textAlign: 'center' }, office: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary }, title: { ...TYPOGRAPHY.heading, color: COLORS.text, textAlign: 'center', marginTop: SPACING.sm },
  meta: { backgroundColor: COLORS.primarySoft, borderRadius: RADIUS.sm, padding: SPACING.md, gap: 3 }, metaText: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary }, bold: { fontWeight: '700', color: COLORS.text }, partSection: { gap: SPACING.md }, part: { ...TYPOGRAPHY.heading, color: COLORS.text, textTransform: 'uppercase', letterSpacing: 0.4, borderBottomWidth: 2, borderBottomColor: COLORS.primary, paddingBottom: SPACING.sm }, heading: { ...TYPOGRAPHY.subheading, color: COLORS.primary },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: SPACING.sm }, metric: { width: '47%', borderWidth: 1, borderColor: COLORS.border, borderRadius: RADIUS.sm, padding: SPACING.md }, metricValue: { ...TYPOGRAPHY.heading, color: COLORS.primary }, metricLabel: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary }, highlights: { borderLeftWidth: 3, borderLeftColor: COLORS.warning, paddingLeft: SPACING.md, gap: SPACING.xs }, highlight: { ...TYPOGRAPHY.body, color: COLORS.textSecondary }, section: { gap: SPACING.sm }, groupRow: { flexDirection: 'row' }, groupCell: { padding: SPACING.xs, backgroundColor: COLORS.primarySoft, color: COLORS.primary, textAlign: 'center', fontWeight: '700', borderWidth: 1, borderColor: COLORS.border }, tableHeader: { flexDirection: 'row', backgroundColor: COLORS.primary }, tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: COLORS.border }, linkedRow: { borderLeftWidth: 3, borderLeftColor: COLORS.primaryLight }, altRow: { backgroundColor: COLORS.surfaceMuted }, cell: { width: 116, padding: SPACING.sm, ...TYPOGRAPHY.caption, color: COLORS.text }, headerCell: { color: COLORS.white, fontWeight: '700' }, empty: { minWidth: 300, padding: SPACING.lg, ...TYPOGRAPHY.body, color: COLORS.textMuted }, legend: { gap: 2, padding: SPACING.sm, backgroundColor: COLORS.surfaceMuted }, legendText: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary }, signature: { gap: SPACING.sm, borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: SPACING.xl }, signatureLine: { ...TYPOGRAPHY.body, color: COLORS.text, borderBottomWidth: 1, borderBottomColor: COLORS.text, paddingTop: SPACING.xxl, paddingBottom: SPACING.xs, textAlign: 'center' }, signatureCaption: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary, textAlign: 'center' }, reviewed: { marginTop: SPACING.lg }, footer: { borderTopWidth: 1, borderTopColor: COLORS.border, paddingTop: SPACING.md, gap: 2 }, footerText: { ...TYPOGRAPHY.caption, color: COLORS.textMuted, textAlign: 'center' },
});
