import type { BsiActivityRow, PriorityPlaceRow, ReinspectionReportRow, RepeatedNonComplianceRow, ReportFilters, ReportInspectionRow, ReportSummary, ReportViewModel } from '@/types/report';
import { formatLocalDate, formatLocalDateTime } from '@/utils/dateTime';

export const resultLabel = (value: string) => value === 'non_compliant' ? 'Non-Compliant' : value === 'for_reinspection' ? 'For Reinspection' : value === 'compliant' ? 'Compliant' : value;
export const riskLabel = (value: string) => value === 'Unclassified' ? 'Not yet classified' : `${value} Risk`;
export const percentage = (value: number | null) => value === null ? 'Not available' : `${Math.round(value)}%`;
const reportingPeriod = (filters: ReportFilters) => `${filters.startDate ? formatLocalDate(filters.startDate) : 'All available dates'} to ${filters.endDate ? formatLocalDate(filters.endDate) : 'present'}`;

export function reportScope(filters: ReportFilters, labels: { barangay: string; inspector: string }, relevant: (keyof ReportFilters)[]) {
  const scope = [`Reporting period: ${reportingPeriod(filters)}`];
  if (relevant.includes('barangayId')) scope.push(`Barangay: ${labels.barangay}`);
  if (relevant.includes('bsiId')) scope.push(`Inspector: ${labels.inspector}`);
  if (relevant.includes('placeType')) scope.push(`Place type: ${filters.placeType === 'all' ? 'All' : filters.placeType}`);
  if (relevant.includes('result')) scope.push(`Result: ${filters.result === 'all' ? 'All' : resultLabel(filters.result)}`);
  if (relevant.includes('riskLevel')) scope.push(`Risk: ${filters.riskLevel === 'all' ? 'All' : riskLabel(filters.riskLevel)}`);
  if (relevant.includes('inspectionType')) scope.push(`Inspection type: ${filters.inspectionType === 'all' ? 'All' : filters.inspectionType === 'reinspection' ? 'Reinspection' : 'Ordinary inspection'}`);
  if (relevant.includes('reinspectionStatus')) scope.push(`Reinspection status: ${filters.reinspectionStatus === 'all' ? 'All' : filters.reinspectionStatus}`);
  if (relevant.includes('accountStatus')) scope.push(`Account status: ${filters.accountStatus === 'all' ? 'All' : filters.accountStatus}`);
  return scope;
}

const base = (title: string, jurisdiction: string, filters: ReportFilters, scope: string[], orientation: ReportViewModel['orientation']): Omit<ReportViewModel, 'metrics' | 'highlights' | 'sections'> => ({ title, jurisdiction, officeLabel: 'Municipal/City Sanitation Office', reportingPeriod: reportingPeriod(filters), generatedAt: new Date().toISOString(), scope, orientation, generatedBy: 'admin' });

export function buildSummaryViewModel(args: { title: string; jurisdiction: string; filters: ReportFilters; scope: string[]; summary: ReportSummary; priority?: PriorityPlaceRow[]; recent?: ReportInspectionRow[]; reinspections?: ReinspectionReportRow[]; repeatedNonCompliance?: RepeatedNonComplianceRow[]; barangayMode?: boolean; includeWorkforce?: boolean }): ReportViewModel {
  const { summary: item } = args;
  const metrics = [
    { label: 'Registered Places', value: String(item.totalRegisteredPlaces) },
    { label: 'Inspected Places', value: String(item.inspectedPlaces) },
    { label: 'Inspections in Period', value: String(item.inspectionsInRange) },
    { label: 'Compliance Rate', value: percentage(item.compliancePercentage) },
    { label: 'High Risk Places', value: String(item.highRiskPlaces) },
    { label: 'Overdue Reinspections', value: String(item.overdueReinspections) },
  ];
  const highlights = [
    `${item.compliant} compliant, ${item.nonCompliant} non-compliant, and ${item.forReinspection} for reinspection.`,
    `${item.lowRiskPlaces} low, ${item.moderateRiskPlaces} moderate, ${item.highRiskPlaces} high, and ${item.unclassifiedRiskPlaces} unclassified current place risks.`,
    `${item.pendingReinspections} pending (${item.overdueReinspections} overdue) and ${item.completedReinspections} completed reinspections.`,
  ];
  const sections = args.barangayMode ? [
    { title: 'Priority Cases', columns: ['Place', 'Status', 'Risk', 'Latest Inspection', 'Reinspection'], rows: (args.priority ?? []).map((row) => [row.placeName, row.status, `${riskLabel(row.riskLevel)} (${percentage(row.latestRiskPercentage)})`, formatLocalDateTime(row.latestInspectionDate, 'Not available'), row.overdue ? 'Overdue' : row.reinspectionStatus ?? 'None']), rowLinks: (args.priority ?? []).map((row) => row.latestInspectionId ? { kind: 'inspection' as const, id: row.latestInspectionId } : null), emptyMessage: 'No priority cases matched this report scope.' },
    { title: 'Recent Inspections', columns: ['Date', 'Place', 'Inspector', 'Type', 'Result', 'Risk', 'Reinspection'], rows: (args.recent ?? []).map((row) => [formatLocalDateTime(row.inspectionDate), row.placeName, row.bsiName, row.inspectionType, resultLabel(row.result), `${riskLabel(row.riskLevel)} (${percentage(row.riskPercentage)})`, row.reinspectionStatus ?? (row.reinspectionRequired ? 'Required' : 'None')]), rowLinks: (args.recent ?? []).map((row) => ({ kind: 'inspection' as const, id: row.id })), emptyMessage: 'No inspections matched this report scope.' },
    ...(args.includeWorkforce === false ? [] : [{ title: 'BSI Assignment Summary', columns: ['Active BSIs', 'Inactive BSIs', 'Barangays with Active BSI', 'Without Active BSI'], rows: [[String(item.activeBsis), String(item.inactiveBsis), String(item.barangaysWithAssignedBsi), String(item.barangaysWithoutAssignedBsi)]] }]),
  ] : [
    { title: 'Coverage and Activity', columns: ['Measure', 'Count'], rows: [['Barangays represented', String(item.totalBarangays)], ['Active barangays with inspections', String(item.activeBarangaysWithInspections)], ['Places not yet inspected', String(item.uninspectedPlaces)], ['Initial inspections', String(item.initialInspections)], ['Regular inspections', String(item.regularInspections)], ['Reinspections', String(item.reinspectionInspections)], ['Active BSIs', String(item.activeBsis)], ['Inactive BSIs', String(item.inactiveBsis)]] },
    { title: 'Priority Action Items', columns: ['Place', 'Barangay', 'Current Status', 'Risk', 'Latest Inspection', 'Reinspection'], rows: (args.priority ?? []).map((row) => [row.placeName, row.barangayName, row.status, `${riskLabel(row.riskLevel)} (${percentage(row.latestRiskPercentage)})`, formatLocalDateTime(row.latestInspectionDate, 'Not available'), row.overdue ? 'Overdue' : row.reinspectionStatus ?? 'None']), rowLinks: (args.priority ?? []).map((row) => row.latestInspectionId ? { kind: 'inspection' as const, id: row.latestInspectionId } : null), emptyMessage: 'No unresolved high-risk or non-compliant cases matched this report scope.' },
    { title: 'Overdue Reinspections', columns: ['Place', 'Barangay', 'Scheduled Date', 'Days Overdue', 'Assigned BSI'], rows: (args.reinspections ?? []).filter((row) => row.status === 'Overdue').map((row) => [row.placeName, row.barangayName, formatLocalDateTime(row.scheduledDate), String(row.daysOverdue), row.bsiName]), rowLinks: (args.reinspections ?? []).filter((row) => row.status === 'Overdue').map((row) => ({ kind: 'inspection' as const, id: row.originalInspectionId })), emptyMessage: 'No overdue reinspections matched this report scope.' },
    { title: 'Repeated Non-Compliance', columns: ['Place', 'Barangay', 'Non-Compliant Inspections', 'Latest Non-Compliant Inspection'], rows: (args.repeatedNonCompliance ?? []).map((row) => [row.placeName, row.barangayName, String(row.occurrences), formatLocalDateTime(row.latestInspectionDate)]), rowLinks: (args.repeatedNonCompliance ?? []).map((row) => ({ kind: 'inspection' as const, id: row.latestInspectionId })), emptyMessage: 'No places have two or more non-compliant inspections in the available history.' },
    { title: 'Barangay Summary', columns: ['Barangay', 'Places', 'Inspections', 'Compliant', 'Non-Compliant', 'For Reinspection', 'High Risk', 'Pending', 'Overdue', 'Active BSIs'], rows: item.barangayCoverage.map((row) => [row.barangayName, String(row.registeredPlaces), String(row.inspectionsInRange), String(row.compliant), String(row.nonCompliant), String(row.forReinspection), String(row.highRisk), String(row.pendingReinspections), String(row.overdueReinspections), String(row.activeBsis)]), emptyMessage: 'No barangay data matched this report scope.' },
  ];
  return { ...base(args.title, args.jurisdiction, args.filters, args.scope, args.barangayMode ? 'landscape' : 'landscape'), metrics, highlights, sections };
}

export function buildInspectionViewModel(title: string, jurisdiction: string, filters: ReportFilters, scope: string[], rows: ReportInspectionRow[], total: number): ReportViewModel {
  const compliant = rows.filter((row) => row.result === 'compliant').length;
  return { ...base(title, jurisdiction, filters, scope, 'landscape'), exportedCount: rows.length, totalCount: total, metrics: [{ label: 'Matching Records', value: String(total) }, { label: 'Exported Records', value: String(rows.length) }, { label: 'Compliant in Export', value: String(compliant) }, { label: 'Reinspections in Export', value: String(rows.filter((row) => row.inspectionType === 'Reinspection').length) }], highlights: rows.length < total ? [`The complete filtered result contains ${total} records; this export includes the first ${rows.length} records under the mobile export safety limit.`] : [`All ${total} filtered records are included.`], sections: [{ title: 'Inspection Register', columns: ['Inspection Date', 'Place Name', 'Place Type', 'Barangay', 'Inspector', 'Inspection Type', 'Result', 'Risk Level', 'Risk %', 'Reinspection Required', 'Reinspection Status', 'Remarks'], rows: rows.map((row) => [formatLocalDateTime(row.inspectionDate), row.placeName, row.placeType, row.barangayName, row.bsiName, row.inspectionType, resultLabel(row.result), riskLabel(row.riskLevel), percentage(row.riskPercentage), row.reinspectionRequired ? 'Yes' : 'No', row.reinspectionStatus ?? 'None', row.remarksSummary ?? 'None']), rowLinks: rows.map((row) => ({ kind: 'inspection', id: row.id })), emptyMessage: 'No records matched the selected filters.' }] };
}

export function buildPriorityViewModel(title: string, jurisdiction: string, filters: ReportFilters, scope: string[], rows: PriorityPlaceRow[], total: number): ReportViewModel {
  return { ...base(title, jurisdiction, filters, scope, 'landscape'), exportedCount: rows.length, totalCount: total, metrics: [{ label: 'Priority Places', value: String(total) }, { label: 'High Risk', value: String(rows.filter((row) => row.riskLevel === 'High').length) }, { label: 'Overdue', value: String(rows.filter((row) => row.overdue).length) }, { label: 'Non-Compliant', value: String(rows.filter((row) => row.status === 'Non-Compliant').length) }], highlights: rows.length < total ? [`Exported ${rows.length} of ${total} priority cases under the mobile safety limit.`] : ['Cases are ordered by high-risk overdue, high-risk, non-compliant overdue, non-compliant, then for-reinspection status.'], sections: [{ title: 'Priority Action Items', columns: ['Priority', 'Place', 'Barangay', 'Latest Inspection', 'Current Status', 'Current Risk', 'Risk %', 'Latest Inspector', 'Pending Date', 'Overdue', 'Important Finding'], rows: rows.map((row, index) => [String(index + 1), row.placeName, row.barangayName, formatLocalDateTime(row.latestInspectionDate, 'Not available'), row.status, riskLabel(row.riskLevel), percentage(row.latestRiskPercentage), row.inspectorName ?? 'Not available', formatLocalDate(row.scheduledDate, 'None'), row.overdue ? 'Yes' : 'No', row.findingSummary ?? 'Not available']), rowLinks: rows.map((row) => row.latestInspectionId ? { kind: 'inspection', id: row.latestInspectionId } : null), emptyMessage: 'No high-risk or unresolved places matched the selected filters.' }] };
}

export function buildReinspectionViewModel(title: string, jurisdiction: string, filters: ReportFilters, scope: string[], rows: ReinspectionReportRow[], total: number): ReportViewModel {
  const section = (name: string, status: ReinspectionReportRow['status']) => { const matching = rows.filter((row) => row.status === status); return { title: name, columns: ['Place', 'Barangay', 'Original Date', 'Original Result', 'Risk', 'Scheduled Date', 'Status', 'Days Overdue', 'Follow-up Date', 'Follow-up Result', 'Assigned BSI'], rows: matching.map((row) => [row.placeName, row.barangayName, formatLocalDateTime(row.originalInspectionDate, 'Not available'), resultLabel(row.originalResult), `${riskLabel(row.originalRiskLevel)} (${percentage(row.originalRiskPercentage)})`, formatLocalDateTime(row.scheduledDate), row.status, row.daysOverdue ? String(row.daysOverdue) : '—', formatLocalDateTime(row.followUpDate, 'Not completed'), row.followUpResult ? resultLabel(row.followUpResult) : 'Not completed', row.bsiName]), rowLinks: matching.map((row) => ({ kind: 'inspection' as const, id: row.completedInspectionId ?? row.originalInspectionId })), emptyMessage: `No ${name.toLowerCase()} matched the selected filters.` }; };
  return { ...base(title, jurisdiction, filters, scope, 'landscape'), exportedCount: rows.length, totalCount: total, metrics: [{ label: 'Matching Records', value: String(total) }, { label: 'Overdue', value: String(rows.filter((row) => row.status === 'Overdue').length) }, { label: 'Pending', value: String(rows.filter((row) => row.status === 'Pending').length) }, { label: 'Completed', value: String(rows.filter((row) => row.status === 'Completed').length) }], highlights: rows.length < total ? [`Exported ${rows.length} of ${total} records under the mobile safety limit.`] : ['Overdue means the scheduled date has passed and the reinspection is not completed.'], sections: [section('Overdue', 'Overdue'), section('Pending', 'Pending'), section('Completed', 'Completed')] };
}

export function buildActivityViewModel(title: string, jurisdiction: string, filters: ReportFilters, scope: string[], rows: BsiActivityRow[], total: number): ReportViewModel {
  return { ...base(title, jurisdiction, filters, scope, 'landscape'), exportedCount: rows.length, totalCount: total, metrics: [{ label: 'BSIs in Scope', value: String(total) }, { label: 'Active', value: String(rows.filter((row) => row.active).length) }, { label: 'Inspections', value: String(rows.reduce((sum, row) => sum + row.inspections, 0)) }, { label: 'Pending Follow-ups', value: String(rows.reduce((sum, row) => sum + row.pendingFollowUps, 0)) }], highlights: ['This report summarizes operational activity only; it does not assign performance scores or rankings.'], sections: [{ title: 'BSI Activity', columns: ['BSI Name', 'Assigned Barangay', 'Account Status', 'Inspections', 'Compliant', 'Non-Compliant', 'For Reinspection', 'Reinspections Completed', 'Pending Follow-up', 'Last Activity'], rows: rows.map((row) => [row.name, row.barangayName, row.active ? 'Active' : 'Inactive', String(row.inspections), String(row.compliant), String(row.nonCompliant), String(row.forReinspection), String(row.reinspectionsCompleted), String(row.pendingFollowUps), formatLocalDateTime(row.lastInspectionDate, 'No activity in period')]), rowLinks: rows.map((row) => ({ kind: 'bsi', id: row.bsiId })), emptyMessage: 'No BSI activity matched the selected filters.' }] };
}
